### ISSUE TITLE
python gmw_inference.py 出错

### ISSUE THREAD

**Issue by dmks** [KuangDD/zhrtvc#101]
@KuangDD 您好，我跑自带的gmw_inference的时候出了以下错误，不知道是不是什么环境没弄好？ 我是在自己的mac的docker上跑的。 另外我是机器学习小白，您可以推荐一些跟本项目相关的学习资料吗？ 🙏

```
root@c14b62320eab:/home/zhrtvc/zhrtvc# python gmw_inference.py
INFO:gmw_inference:gmw_inference.py
load phrase: 36776it [00:00, 65486.45it/s]
load pinyin: 41453it [00:00, 61164.60it/s]
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
DEBUG:jieba:Loading model from cache /tmp/jieba.cache
Loading model cost 0.603 seconds.
DEBUG:jieba:Loading model cost 0.603 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
Loaded encoder "ge2e_pretrained.pt" trained to step 1564501
/home/zhrtvc/zhrtvc/encoder/audio.py:105: RuntimeWarning: divide by zero encountered in log10
  wave_dBFS = 20 * np.log10(rms / int16_max)
/home/zhrtvc/zhrtvc/encoder/audio.py:109: RuntimeWarning: invalid value encountered in multiply
  return wav * (10 ** (dBFS_change / 20))
Traceback (most recent call last):
  File "gmw_inference.py", line 239, in <module>
    mels, mels_postnet, gates, alignments = mellotron.generate_mel(text_data, style_data, speaker_data, f0_data)
  File "/home/zhrtvc/zhrtvc/mellotron/inference.py", line 81, in generate_mel
    mels, mels_postnet, gates, alignments = _model.inference((text, style, speaker, f0))
  File "/home/zhrtvc/zhrtvc/mellotron/model.py", line 657, in inference
    embedded_text = self.encoder.inference(embedded_inputs)
  File "/home/zhrtvc/zhrtvc/mellotron/model.py", line 216, in inference
    outputs, _ = self.lstm(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 646, in forward
    real_hidden_size = self.proj_size if self.proj_size > 0 else self.hidden_size
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'LSTM' object has no attribute 'proj_size'
```

**Comment by KuangDD** [comment]
torch版本太高，建议用torch==1.7的版本。

**Comment by sexchen** [comment]
> torch版本太高，建议用torch==1.7的版本

我按照教程安装了依赖 但是无法启动。
```
(zhrtvc) C:\zhrtvc-master\zhrtvc>gmw_inference.py
Unable to create process using 'usr/bin/env python "C:\zhrtvc-master\zhrtvc\gmw_
inference.py" '
```

模块列表
```
(zhrtvc) C:\zhrtvc-master\zhrtvc>pip list
Package              Version
-------------------- -------------------
absl-py              0.12.0
appdirs              1.4.4
astor                0.8.1
audioread            2.1.9
aukit                1.4.4
cached-property      1.5.2
certifi              2020.12.5
cffi                 1.14.5
chardet              4.0.0
cycler               0.10.0
dataclasses          0.6
decorator            5.0.9
dill                 0.3.3
dotmap               1.3.23
future               0.18.2
gast                 0.2.2
google-pasta         0.2.0
grpcio               1.37.1
h5py                 3.2.1
hanziconv            0.3.2
idna                 2.10
importlib-metadata   4.0.1
inflect              4.1.0
jieba                0.42.1
joblib               1.0.1
jsonpatch            1.32
jsonpointer          2.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.3.1
librosa              0.8.0
llvmlite             0.31.0
Markdown             3.3.4
matplotlib           3.1.1
more-itertools       8.7.0
multiprocess         0.70.11.1
music21              6.1.0
numba                0.48.0
numpy                1.20.3
opt-einsum           3.3.0
packaging            20.9
pandas               0.25.1
phkit                0.2.7
Pillow               8.2.0
pip                  21.0.1
pooch                1.3.0
protobuf             3.17.0
pycparser            2.20
pydub                0.24.1
pyparsing            2.4.7
pypinyin             0.41.0
python-dateutil      2.8.1
pytz                 2021.1
PyYAML               5.4.1
pyzmq                22.0.3
requests             2.25.1
resampy              0.2.2
scikit-learn         0.24.2
scipy                1.3.1
setproctitle         1.2.2
setuptools           52.0.0.post20210125
six                  1.16.0
sounddevice          0.4.1
SoundFile            0.10.3.post1
tensorboard          1.15.0
tensorflow           1.15.2
tensorflow-estimator 1.15.1
termcolor            1.1.0
threadpoolctl        2.1.0
torch                1.7.0+cpu
torchaudio           0.7.0
torchfile            0.1.0
torchvision          0.8.0
tornado              6.1
tqdm                 4.36.1
typing-extensions    3.10.0.0
umap-learn           0.1.1
Unidecode            1.1.1
urllib3              1.26.4
visdom               0.1.8.9
webcolors            1.11.1
websocket-client     0.59.0
Werkzeug             2.0.1
wheel                0.36.2
wincertstore         0.2
wrapt                1.12.1
xmltodict            0.12.0
zipp                 3.4.1
```
