### ISSUE TITLE
用您提供的权值mellotron-400000.pt微调时报错

### ISSUE THREAD

**Issue by fanghaiquan1** [KuangDD/zhrtvc#112]
大佬，您好！用您提供的权值mellotron-400000.pt微调时报错。
用我自己训练的标贝1万条得到的权值去微调能正常运行，不知道哪里需要调？请您帮忙指导

报错如下：

Traceback (most recent call last):
  File "mellotron_train.py", line 87, in <module>
    train(hparams=hparams, **args.__dict__)
  File "/mnt/lustrefs/home/*/zhrtvc-master/zhrtvc/mellotron/train.py", line 309, in train
    checkpoint_path, model, hparams.ignore_layers)
  File "/mnt/lustrefs/home/*/zhrtvc-master/zhrtvc/mellotron/train.py", line 116, in warm_start_model
    model.load_state_dict(model_dict)
  File "/mnt/lustrefs/home/*/.conda/envs/FH137/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	size mismatch for decoder.attention_rnn.weight_ih: copying a param with shape torch.Size([4096, 832]) from checkpoint, the shape in current model is torch.Size([4096, 800]).
	size mismatch for decoder.attention_layer.memory_layer.linear_layer.weight: copying a param with shape torch.Size([128, 576]) from checkpoint, the shape in current model is torch.Size([128, 544]).
	size mismatch for decoder.decoder_rnn.weight_ih: copying a param with shape torch.Size([4096, 1600]) from checkpoint, the shape in current model is torch.Size([4096, 1568]).
	size mismatch for decoder.linear_projection.linear_layer.weight: copying a param with shape torch.Size([80, 1600]) from checkpoint, the shape in current model is torch.Size([80, 1568]).
	size mismatch for decoder.gate_layer.linear_layer.weight: copying a param with shape torch.Size([1, 1600]) from checkpoint, the shape in current model is torch.Size([1, 1568]).
	size mismatch for speaker_embedding.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).

**Comment by fanghaiquan1** [comment]
可能参数设置方面需要参考您之前的，这样才能对上。您看能否分享hparams.json这个文件

**Comment by KuangDD** [comment]
我分享的目录里面有个metadata目录，里面有hparams.json文件，这里是参数，可以load这里的参数训练（修改部分涉及路径的参数）。

**Comment by fanghaiquan1** [comment]
好的，谢谢！明白了
