### ISSUE TITLE
运行工具箱 vocoder 出错

### ISSUE THREAD

**Issue by Simngscat** [KuangDD/zhrtvc#14]
win10系统 
jieba add word: 100%|████████████████| 398815/398815 [00:05<00:00, 77929.30it/s]
Traceback (most recent call last):
  File "G:\Github\RTVC-zh\zhrtvc\toolbox\__init__.py", line 319, in vocode
    wav = Synthesizer.griffin_lim(spec)
  File "G:\Github\RTVC-zh\zhrtvc\synthesizer\inference.py", line 143, in griffin_lim
    return audio.inv_melspectrogram(mel, hparams)
  File "G:\Github\RTVC-zh\zhrtvc\synthesizer\utils\audio.py", line 41, in inv_melspectrogram
    wav = inv_mel_spectrogram(mel, melgan_hparams)
  File "G:\Github\Real-Time-Voice-Cloning\venv\lib\site-packages\aukit\audio_griffinlim.py", line 66, in inv_mel_spectrogram
    S = _mel_to_linear(_db_to_amp(D + hparams.ref_level_db), hparams)  # Convert back to linear
  File "G:\Github\Real-Time-Voice-Cloning\venv\lib\site-packages\aukit\audio_griffinlim.py", line 353, in _mel_to_linear
    _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
  File "<__array_function__ internals>", line 6, in pinv
  File "G:\Github\Real-Time-Voice-Cloning\venv\lib\site-packages\numpy\linalg\linalg.py", line 1961, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
  File "<__array_function__ internals>", line 6, in svd
  File "G:\Github\Real-Time-Voice-Cloning\venv\lib\site-packages\numpy\linalg\linalg.py", line 1626, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "G:\Github\Real-Time-Voice-Cloning\venv\lib\site-packages\numpy\linalg\linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

**Comment by KuangDD** [comment]
传入的spec是什么shape的，可能频谱shape不匹配。

**Comment by Simngscat** [comment]
@KuangDD    (80, 139)
我刚在ubuntu环境下重试了，正常运行， shape一样，所以这是哪里的问题

 但是在ubuntu系统碰到了另一个头疼的问题，sounddevice检测不到输出设备，只能保存下来听

**Comment by KuangDD** [comment]
pyaudio暂不支持python37以上版本直接pip安装，需要下载whl文件安装，下载路径：https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio

sounddevice依赖pyaudio。

**Comment by Simngscat** [comment]
@KuangDD  确定两个系统都装了，win10 是下载whl安装的，后来又装了python36，以36版本建了环境，还是错误
ubuntu也装了

**Comment by Simngscat** [comment]
我尝试把环境换成了 anaconda，根据anaconda官网提示安装了 sounddevice，可以检测到设备了
import sounddevice as sd
sd.query_hostapis()
({'name': 'ALSA', 'devices': [0, 1, 2, 3, 4, 5, 6, 7, 8], 'default_input_device': 8, 'default_output_device': 8}, {'name': 'OSS', 'devices': [], 'default_input_device': -1, 'default_output_device': -1})
sd.query_devices()
  0 HDA NVidia: HDMI 0 (hw:0,3), ALSA (0 in, 8 out)
  1 HDA NVidia: HDMI 1 (hw:0,7), ALSA (0 in, 2 out)
  2 HDA NVidia: HDMI 2 (hw:0,8), ALSA (0 in, 8 out)
  3 HD-Audio Generic: ALC892 Analog (hw:1,0), ALSA (2 in, 6 out)
  4 HD-Audio Generic: ALC892 Digital (hw:1,1), ALSA (0 in, 2 out)
  5 HD-Audio Generic: ALC892 Alt Analog (hw:1,2), ALSA (2 in, 0 out)
  6 hdmi, ALSA (0 in, 8 out)
  7 pulse, ALSA (32 in, 32 out)
* 8 default, ALSA (32 in, 32 out)

**Comment by Simngscat** [comment]
@KuangDD 谢谢回复，我把环境换成Anaconda，win10下能正常运行了
