### ISSUE TITLE
Load了一些音频后，出现报错

### ISSUE THREAD

**Issue by y122302868** [KuangDD/zhrtvc#15]
Traceback (most recent call last):
  File "D:\python3\zhrtvc-master\zhrtvc\toolbox\__init__.py", line 96, in <lambda>
    self.ui.browser_load_button.clicked.connect(lambda: self.load_from_browser())
  File "D:\python3\zhrtvc-master\zhrtvc\toolbox\__init__.py", line 169, in load_from_browser
    self.add_real_utterance(wav, name, speaker_name)
  File "D:\python3\zhrtvc-master\zhrtvc\toolbox\__init__.py", line 243, in add_real_utterance
    self.ui.draw_umap_projections(self.utterances)
  File "D:\python3\zhrtvc-master\zhrtvc\toolbox\ui.py", line 127, in draw_umap_projections
    projections = reducer.fit_transform(embeds)
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\umap\umap_.py", line 2012, in fit_transform
    self.fit(X, y)
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\umap\umap_.py", line 1777, in fit
    self.verbose,
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\umap\umap_.py", line 597, in fuzzy_simplicial_set
    X, n_neighbors, metric, metric_kwds, angular, random_state, verbose=verbose
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\umap\umap_.py", line 277, in nearest_neighbors
    knn_indices = fast_knn_indices(X, n_neighbors)
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x000001D37DAE1C18>) with argument(s) of type(s): (array(float64, 1d, C))
 * parameterized
In definition 0:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "..\..\..\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py", line 169:
    def run_quicksort(A):
        <source elided>

        stack = [Partition(zero, zero)] * MAX_STACK
        ^

[1] During: lowering "$24.5 = build_list(items=[Var($24.4, D:\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py (169))])" at D:\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py (169)
    raised from D:\pythonenv\zhrtvc_new\lib\site-packages\numba\six.py:669
In definition 1:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "..\..\..\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py", line 169:
    def run_quicksort(A):
        <source elided>

        stack = [Partition(zero, zero)] * MAX_STACK
        ^

[1] During: lowering "$24.5 = build_list(items=[Var($24.4, D:\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py (169))])" at D:\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\quicksort.py (169)
    raised from D:\pythonenv\zhrtvc_new\lib\site-packages\numba\six.py:669
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x000001D37DAE1C18>)
[2] During: typing of call at D:\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\arrayobj.py (4809)

File "..\..\..\pythonenv\zhrtvc_new\lib\site-packages\numba\targets\arrayobj.py", line 4809:
    def array_argsort_impl(arr):
        return sort_func(arr)
        ^

[1] During: lowering "$46.8 = call $46.5($46.4, func=$46.5, args=[Var($46.4, D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (32))], kws=[('kind', Var($const46.6, D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (32)))], vararg=None)" at D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (32)
[2] During: lowering "id=0[LoopNest(index_variable = parfor_index.16, range = (0, $28.6, 1))]{46: <ir.Block at D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (30)>}Var(parfor_index.16, D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (30))" at D:\pythonenv\zhrtvc_new\lib\site-packages\umap\utils.py (30)

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

toolbox被错误日志撑大，不能正常使用

**Comment by KuangDD** [comment]
检查一下语音文件格式，重启一下。

**Comment by y122302868** [comment]
data中的数据是从文档下载下来直接替换的，我发现好像并不是load的问题，是在画散点图的时候报错的，只要播放超过4个就会报错
reducer = umap.UMAP(int(np.ceil(np.sqrt(len(embeds)))), metric="cosine")
            # reducer = TSNE()
            projections = reducer.fit_transform(embeds)
只要走到这里就会有问题
![image](https://user-images.githubusercontent.com/56955508/84968841-f76bfd80-b149-11ea-920f-7c208f43e15f.png)
这个依赖我也有安装啊，不知道问题出在哪里

**Comment by y122302868** [comment]
工具箱下面的散点图一直渲染不出来
我发现只安装umap_learn会报这个问题
再安装umap会报AttributeError: module 'umap' has no attribute 'UMAP'
请问一下作者，是如何安装umap_learn和umap的呢

**Comment by KuangDD** [comment]
pip install umap-learn

需要py36以上版本。
