### ISSUE TITLE
在执行synthesizer_preprocess_embeds.py时出现pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by y122302868** [KuangDD/zhrtvc#16]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\tools\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\tools\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\tools\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\tools\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\tools\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\tools\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\tools\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python3\zhrtvc-master\zhrtvc\synthesizer_preprocess_embeds.py", line 1, in <module>
    from synthesizer.preprocess import create_embeddings
  File "D:\python3\zhrtvc-master\zhrtvc\synthesizer\preprocess.py", line 2, in <module>
    from synthesizer.utils import audio
  File "D:\python3\zhrtvc-master\zhrtvc\synthesizer\utils\audio.py", line 3, in <module>
    from aukit.audio_spectrogram import mel_spectrogram
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\aukit\__init__.py", line 34, in <module>
    from .audio_normalizer import preprocess_wav, remove_silence, tune_volume
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\aukit\audio_normalizer.py", line 26, in <module>
    import webrtcvad
  File "D:\pythonenv\zhrtvc_new\lib\site-packages\webrtcvad.py", line 8, in <module>
    __version__ = pkg_resources.get_distribution('webrtcvad').version
  File "D:\tools\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "D:\tools\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "D:\tools\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "D:\tools\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application

**Comment by KuangDD** [comment]
装一下依赖webrtcvad。

**Comment by y122302868** [comment]
webrtcvad这个依赖已经装过了
![image](https://user-images.githubusercontent.com/56955508/84969075-87aa4280-b14a-11ea-8902-161e52ddc0b8.png)

**Comment by KuangDD** [comment]
重新安装一下。
