### ISSUE TITLE
"pip3 install -r requirements.txt" 报错 "ModuleNotFoundError: No module named 'hanziconv'"

### ISSUE THREAD

**Issue by neruthes** [KuangDD/zhrtvc#18]
```
$ pip3 install -r requirements.txt 
Collecting cycler
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting sounddevice
  Using cached sounddevice-0.3.15-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.cp37.cp38.cp39.pp27.pp32.pp33.pp34.pp35.pp36.pp37-none-macosx_10_6_x86_64.whl (77 kB)
Collecting tensorflow<=1.15.2
  Downloading tensorflow-1.15.2-cp37-cp37m-macosx_10_11_x86_64.whl (123.3 MB)
     |████████████████████████████████| 123.3 MB 11.3 MB/s 
Collecting matplotlib
  Downloading matplotlib-3.2.2-cp37-cp37m-macosx_10_9_x86_64.whl (12.5 MB)
     |████████████████████████████████| 12.5 MB 10.6 MB/s 
Collecting umap_learn
  Using cached umap-learn-0.4.4.tar.gz (69 kB)
Collecting phkit>=0.2.1
  Using cached phkit-0.2.1.tar.gz (3.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/setup.py'"'"'; __file__='"'"'/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/pip-egg-info
         cwd: /private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/setup.py", line 26, in <module>
        from phkit import __version__ as phkit_version
      File "/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/phkit/__init__.py", line 59, in <module>
        from phkit.chinese import __doc__ as doc_chinese
      File "/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/phkit/chinese/__init__.py", line 32, in <module>
        from .convert import fan2jian, jian2fan, quan2ban, ban2quan
      File "/private/var/folders/rn/4pwwhb8n7zd71n7xxbft_yz80000gn/T/pip-install-loihppbi/phkit/phkit/chinese/convert.py", line 11, in <module>
        from hanziconv import hanziconv
    ModuleNotFoundError: No module named 'hanziconv'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

不常用 Python，毫无头绪 🤔

环境：

- Mac OS OX 10.13.6 High Sierra
- ZSH
- `pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`
- `Python 3.6.1`

**Comment by KuangDD** [comment]
试试先安装hanziconv，安装过程中如果报错缺包，那先安装缺少的包试试。

pip install hanziconv

**Comment by neruthes** [comment]
感谢。通过手动安装依赖，pip3 install 过程没再出问题。现在的最新进展是，pip3 找不到版本足够低的 tensorflow（<= 1.15.2），尝试取消版本限制后安装了的 2.2.0 后运行 `python3 demo_cli.py` 时又遇到：

```
Traceback (most recent call last):
  File "demo_cli.py", line 3, in <module>
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
```

可能最好的方案是安装足够低版本的 tensorflow？至于具体的安装方法……

**Comment by KuangDD** [comment]
tensorflow用v1的即可。

刚刚更新了依赖，可以用最新的依赖试试。

pip install -r requirements.txt

**Comment by neruthes** [comment]
经过一些尝试，pip3 能够找到指定版本的 tensorflow，但是……

```
Collecting jsonpointer>=1.9
  Downloading jsonpointer-2.0-py2.py3-none-any.whl (7.6 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->inflect->phkit>=0.2.2->-r requirements.txt (line 6)) (3.1.0)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy from https://files.pythonhosted.org/packages/5c/f5/0e5e57fa7683cf0e5036320f4676cd7e3dbd9ab8c17ada541c2bb5ebed5e/numpy-1.19.0-cp37-cp37m-macosx_10_9_x86_64.whl#sha256=d97a86937cf9970453c3b62abb55a6475f173347b4cde7f8dcdb48c8e1b9952d (from -r requirements.txt (line 14)):
        Expected sha256 d97a86937cf9970453c3b62abb55a6475f173347b4cde7f8dcdb48c8e1b9952d
             Got        0896ae47cd4201582da16b75187fdb56cdd1c16444d2528f8db079a3b2babce4

    scipy from https://files.pythonhosted.org/packages/11/b9/a79caafbd276b920ef2692b4b8602cc9cd9bd078f8c726d254354be2c2cb/scipy-1.5.0-cp37-cp37m-macosx_10_9_x86_64.whl#sha256=ae24f16056c87e7f086a56a7aaf6e65e4626ac70b7e08d7f54e078693abcf778 (from -r requirements.txt (line 15)):
        Expected sha256 ae24f16056c87e7f086a56a7aaf6e65e4626ac70b7e08d7f54e078693abcf778
             Got        fb939e390527b10496bede3d8efbd5bef6d1520f0d318940d317de2cabac5194

    PyQt5<=5.15.0 from https://files.pythonhosted.org/packages/6d/f6/bbb2d6fcd18318c5118f2735b68a12ed615ea7c55abc3f9f56173b787750/PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl#sha256=14be35c0c1bcc804791a096d2ef9950f12c6fd34dd11dbe61b8c769fefcdf98c (from -r requirements.txt (line 18)):
        Expected sha256 14be35c0c1bcc804791a096d2ef9950f12c6fd34dd11dbe61b8c769fefcdf98c
             Got        beedc44ca86bd51739e2935c978f1fb6bec0a08ed3fe302676b791e4d62f98bb

    torch from https://files.pythonhosted.org/packages/5d/ad/51da3af99a515c31226f50c37d85e63423f9e28174c2984e11e4fb47ae01/torch-1.5.1-cp37-none-macosx_10_9_x86_64.whl#sha256=bb2a3e6c9c9dbfda856bd1b1a55d88789a9488b569ffba9cd6d9aa536ef866ba (from -r requirements.txt (line 21)):
        Expected sha256 bb2a3e6c9c9dbfda856bd1b1a55d88789a9488b569ffba9cd6d9aa536ef866ba
             Got        4ec6d9b50abe250c488046fbd49567bea473dc448a3f7c130f85844c02b08eb1
```

可能是我受到了中间人攻击，也可能是某些依赖管理系统中的 hash 记录有误。或许我应该尝试手动安装这些被递归依赖的包？

**Comment by KuangDD** [comment]
你的这些问题我都没遇到过，我是用pip即可。
