### ISSUE TITLE
发生错误 SVD did not converge

### ISSUE THREAD

**Issue by 0fengzi0** [KuangDD/zhrtvc#20]
```
Saving alignment, Mel-Spectrograms and griffin-lim inverted waveform..
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Exiting due to exception: SVD did not converge
Traceback (most recent call last):
  File "E:\project\python\zhrtvc\zhrtvc\synthesizer\train.py", line 365, in train
    wav = audio.inv_mel_spectrogram(mel_prediction.T, hparams)
  File "E:\conda_env\tts\lib\site-packages\aukit\audio_griffinlim.py", line 66, in inv_mel_spectrogram
    S = _mel_to_linear(_db_to_amp(D + hparams.ref_level_db), hparams)  # Convert back to linear
  File "E:\conda_env\tts\lib\site-packages\aukit\audio_griffinlim.py", line 353, in _mel_to_linear
    _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
  File "<__array_function__ internals>", line 6, in pinv
  File "E:\conda_env\tts\lib\site-packages\numpy\linalg\linalg.py", line 2003, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
  File "<__array_function__ internals>", line 6, in svd
  File "E:\conda_env\tts\lib\site-packages\numpy\linalg\linalg.py", line 1661, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "E:\conda_env\tts\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
INFO:tensorflow:Error reported to Coordinator: <class 'numpy.linalg.LinAlgError'>, SVD did not converge
INFO:tensorflow:Error reported to Coordinator: <class 'numpy.linalg.LinAlgError'>, SVD did not converge
2020-06-28 12:54:45.401507: W tensorflow/core/kernels/queue_base.cc:277] _1_datafeeder/eval_queue: Skipping cancelled enqueue attempt with queue not closed
2020-06-28 12:54:45.401823: W tensorflow/core/kernels/queue_base.cc:277] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
```
使用CPU训练时这个错误条过了,使用GPU训练在这里停止了,使用工具箱合成音频时也有这个问题
系统是win10,cuda10.1,py3.7,GTX 960M 4G显存,这是conda导出的配置
```
name: E:\conda_env\tts
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.6.20=py37_0
  - openssl=1.1.1g=he774522_0
  - pip=20.1.1=py37_1
  - powershell_shortcut=0.0.1=3
  - python=3.7.7=h81c818b_4
  - setuptools=47.3.1=py37_0
  - sqlite=3.32.3=h2a8f88b_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - audioread==2.1.8
    - aukit==1.4.2
    - cffi==1.14.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.20
    - decorator==4.4.2
    - dill==0.3.2
    - dotmap==1.3.17
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - h5py==2.10.0
    - hanziconv==0.3.2
    - idna==2.9
    - importlib-metadata==1.6.1
    - inflect==4.1.0
    - jieba==0.42.1
    - joblib==0.15.1
    - jsonpatch==1.26
    - jsonpointer==2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - librosa==0.7.2
    - llvmlite==0.31.0
    - markdown==3.2.2
    - matplotlib==3.2.2
    - mock==4.0.2
    - multiprocess==0.70.10
    - numba==0.48.0
    - numpy==1.19.0
    - opt-einsum==3.2.1
    - packaging==20.4
    - phkit==0.2.2
    - pillow==7.1.2
    - protobuf==3.12.2
    - pyaudio==0.2.11
    - pycparser==2.20
    - pydub==0.24.1
    - pyparsing==2.4.7
    - pypinyin==0.38.0
    - pyqt5==5.15.0
    - pyqt5-sip==12.8.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyworld==0.2.10
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - requests==2.24.0
    - resampy==0.2.2
    - scikit-learn==0.23.1
    - scipy==1.5.0
    - sip==5.3.0
    - six==1.15.0
    - sounddevice==0.3.15
    - soundfile==0.10.3.post1
    - tbb==2019.0
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - toml==0.10.1
    - torch==1.5.1+cu101
    - torchfile==0.1.0
    - torchvision==0.6.1+cu101
    - tornado==6.0.4
    - tqdm==4.46.1
    - umap==0.1.1
    - umap-learn==0.4.4
    - unidecode==1.1.1
    - urllib3==1.25.9
    - visdom==0.1.8.9
    - webrtcvad==2.0.10
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0
prefix: E:\conda_env\tts
```
另外我该如何调节batch size,我尝试过修改```synthesizer\hparams.py```中的参数,甚至修改到了4依然会提示oom错误

**Comment by KuangDD** [comment]
numpy.linalg.LinAlgError: SVD did not converge报错的问题可能是数据存在空值，可以用样本数据训练试试。

OOM错误确认一下GPU内存多大，把max_mel_frames调小试试。

**Comment by 0fengzi0** [comment]
感谢您的回复,我重新检查了我的数据,发现不是数据的问题,我重新配置环境后SVD did not converge问题解决,非常感谢您的回复
