### ISSUE TITLE
预处理语料报错python3  synthesizer_preprocess_audio.py

### ISSUE THREAD

**Issue by leslie2046** [KuangDD/zhrtvc#21]
wav_fpath: ../data/samples/aliaudio/Yina/006171.mp3
data: ['aliaudio/Yina/006171.mp3', '虎父无犬子，两只小藏獒是标准的铁包金，属“怪兽”血系。']
error: unsupported operand type(s) for *: 'DotMap' and 'float'

**Comment by leslie2046** [comment]
代码没有做任何改动，用的样例语料，用的python3.7,安装的也是按照requirements_with_version.txt里规定的包

**Comment by leslie2046** [comment]
[root@localhost zhrtvc]# pip3 list
Package              Version
-------------------- ------------
absl-py              0.9.0
anaconda             0.0.1.1
astor                0.8.1
audioread            2.1.8
aukit                1.4.2
certifi              2020.6.20
cffi                 1.14.0
chardet              3.0.4
cycler               0.10.0
Cython               0.29.20
decorator            4.4.2
dill                 0.3.2
dotmap               1.3.17
future               0.18.2
gast                 0.2.2
gevent               20.6.2
google-pasta         0.2.0
greenlet             0.4.16
grpcio               1.30.0
h5py                 2.10.0
hanziconv            0.3.2
idna                 2.10
importlib-metadata   1.7.0
inflect              4.1.0
jieba                0.42.1
joblib               0.15.1
jsonpatch            1.26
jsonpointer          2.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.2.0
librosa              0.7.2
llvmlite             0.31.0
Markdown             3.2.2
matplotlib           2.2.3
mock                 4.0.2
multiprocess         0.70.9
numba                0.46.0
numpy                1.18.4
opt-einsum           3.2.1
packaging            20.4
phkit                0.2.2
Pillow               7.1.2
pip                  20.1.1
protobuf             3.12.2
PyAudio              0.2.11
pycparser            2.20
pydub                0.23.1
pyparsing            2.4.7
pypinyin             0.38.0
PyQt5                5.15.0
PyQt5-sip            12.8.0
python-dateutil      2.8.1
pytz                 2020.1
pyworld              0.2.10
PyYAML               5.3.1
pyzmq                19.0.1
requests             2.24.0
resampy              0.2.2
scikit-learn         0.23.1
scipy                1.4.1
sequitur             1.0a1
setuptools           47.3.1
sip                  5.3.0
six                  1.15.0
sounddevice          0.3.14
SoundFile            0.10.3.post1
tbb                  2020.0.133
tensorboard          1.15.0
tensorflow           1.13.2
tensorflow-estimator 1.15.1
tensorflow-gpu       1.15.2
termcolor            1.1.0
threadpoolctl        2.1.0
toml                 0.10.1
torch                1.5.0
torchfile            0.1.0
torchvision          0.6.1
tornado              6.0.4
tqdm                 4.26.0
umap                 0.1.1
umap-learn           0.4.4
Unidecode            1.1.1
urllib3              1.25.9
visdom               0.1.8.9
webrtcvad            2.0.10
websocket            0.2.1
websocket-client     0.57.0
Werkzeug             1.0.1
wheel                0.34.2
wrapt                1.12.1
zipp                 3.1.0
zope.event           4.4
zope.interface       5.1.0

**Comment by leslie2046** [comment]
python3 synthesizer/utils/audio.py 
Traceback (most recent call last):
  File "synthesizer/utils/audio.py", line 50, in <module>
    mel = melspectrogram(wav)
  File "synthesizer/utils/audio.py", line 34, in melspectrogram
    mel = mel_spectrogram(wav, melgan_hparams)
  File "/usr/local/lib/python3.7/site-packages/aukit/audio_spectrogram.py", line 70, in mel_spectrogram
    S = amp_to_db(linear_to_mel(np.abs(D), hparams))
  File "/usr/local/lib/python3.7/site-packages/aukit/audio_spectrogram.py", line 166, in linear_to_mel
    return np.dot(mel_basis, spectrogram)
  File "<__array_function__ internals>", line 6, in dot
TypeError: unsupported operand type(s) for *: 'DotMap' and 'float'

**Comment by KuangDD** [comment]
麻烦打印一下np.dot(mel_basis, spectrogram)里面的mel_basis和spectrogram是什么？
我没遇到过这样的问题。

**Comment by leslie2046** [comment]
加了打印mel_basis,打印出来是dotMap()，然后我把synthesizer/utils/audio.py里面，增加了下面4个参数，就不报错了，我也不找到这样改对不对
my_hp = {
    "inv_mel_basis":None,
    "mel_basis":None,
    "num_mels":80,
    "center":True,

**Comment by leslie2046** [comment]
还有啊，synthesizer/utils/audio.py为什么默认是采样率是22050,而样例语料是16K的，这里不需要改成16000吗

**Comment by KuangDD** [comment]
默认的melgan_hparams不是有my_hp里面的参数的吗。

这套参数是兼容melgan的publish的声码器的，采样率用22050，语音转频谱和频谱转语音的参数相同就没问题的。

**Comment by leslie2046** [comment]
我加上这
    "inv_mel_basis":None,
    "mel_basis":None,
    "num_mels":80,
    "center":True,
四行才不会报错哦，好奇怪，你居然没遇到过这个问题
my_hp = {
    "inv_mel_basis":None,
    "mel_basis":None,
    "num_mels":80,
    "center":True,
    "n_fft": 1024, 
    "hop_size": 256, 
    "win_size": 1024,
    "sample_rate": _sr,
    "fmin": 0, "fmax": _sr // 2,
    "preemphasize": False, 
    'symmetric_mels': True,
    'signal_normalization': False,
    'allow_clipping_in_normalization': False,
    'ref_level_db': 0,
    '__file__': __file__
}

**Comment by leslie2046** [comment]
> 
> 
> 默认的melgan_hparams不是有my_hp里面的参数的吗。
> 
> 这套参数是兼容melgan的publish的声码器的，采样率用22050，语音转频谱和频谱转语音的参数相同就没问题的。

你的意思是训练synthesizer的语料是16K的，也可以设置成22050来进行语言频谱转换吗？
你说的publish的vocoder模型是melgan_multi_speaker.pt吗，这个模型跟22050有什么关系

**Comment by KuangDD** [comment]
是的，这个模型训练时候的采样率是22050。

**Comment by leslie2046** [comment]
> 
> 
> 是的，这个模型训练时候的采样率是22050。

所以我如果改成16000的话，只能用一个16K训练的声码器来配合了

**Comment by KuangDD** [comment]
from aukit.audio_griffinlim import default_hparams
这里有那些参数了的，而且melspectrogram的函数的hparams参数是架空的，用的是melgan_hparams。

**Comment by leslie2046** [comment]
我看了下导致报错的原因就是因为hparams.mel_basis不为None,导致走了下面那个分支
/usr/local/lib/python3.7/site-packages/aukit/audio_spectrogram.py


def linear_to_mel(spectrogram, hparams=None):
    hparams = hparams or default_hparams
    if hparams.mel_basis is None:
        mel_basis = build_mel_basis(hparams)
    else:
        mel_basis = hparams.mel_basis
    return np.dot(mel_basis, spectrogram)

**Comment by wgc7998** [comment]
我也是同样的报错，然后加了那四个参数，就可以正常预处理了。。
