### ISSUE TITLE
训练synthesizer经常出这种错误

### ISSUE THREAD

**Issue by leslie2046** [KuangDD/zhrtvc#22]
Generated 8 train batches of size 64 in 0.734 sec
Step   40226 [0.972 sec/step, loss=0.37396, avg_loss=0.36119]
Step   40227 [0.988 sec/step, loss=0.29966, avg_loss=0.36055]
Step   40228 [0.981 sec/step, loss=0.36604, avg_loss=0.36097]
Step   40229 [0.982 sec/step, loss=0.35469, avg_loss=0.36087]
Step   40230 [0.978 sec/step, loss=0.36606, avg_loss=0.36084]
Step   40231 [0.980 sec/step, loss=0.37564, avg_loss=0.36084]
Step   40232 [0.982 sec/step, loss=0.37475, avg_loss=0.36090]
Step   40233 [0.982 sec/step, loss=0.36646, avg_loss=0.36098]
  0%|                     | 0/512 [00:00<?, ?it/s]Step   40234 [0.977 sec/step, loss=0.36494, avg_loss=0.36085]
Step   40235 [0.978 sec/step, loss=0.37314, avg_loss=0.36072]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40236 [0.984 sec/step, loss=0.35602, avg_loss=0.36061]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40237 [0.981 sec/step, loss=0.37309, avg_loss=0.36067]
Step   40238 [0.966 sec/step, loss=0.37494, avg_loss=0.36143]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40239 [0.968 sec/step, loss=0.37094, avg_loss=0.36148]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40240 [0.970 sec/step, loss=0.37338, avg_loss=0.36148]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40241 [0.972 sec/step, loss=0.36823, avg_loss=0.36150]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Step   40242 [0.986 sec/step, loss=0.29881, avg_loss=0.36102]
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x7f8f48e000d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tkinter/__init__.py", line 3504, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
已放弃(吐核)

**Comment by KuangDD** [comment]
tkinter这个包报错，一些依赖没安装好。
