### ISSUE TITLE
raise LinAlgError("SVD did not converge")

### ISSUE THREAD

**Issue by wenshitao** [KuangDD/zhrtvc#29]
训练测试数据时报错，请修复谢谢
Saving alignment, Mel-Spectrograms and griffin-lim inverted waveform..
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Exiting due to exception: SVD did not converge
Traceback (most recent call last):
  File "E:\zhrtvc-master\zhrtvc\synthesizer\train.py", line 365, in train
    wav = audio.inv_mel_spectrogram(mel_prediction.T, hparams)
  File "D:\ana\lib\site-packages\aukit\audio_griffinlim.py", line 66, in inv_mel_spectrogram
    S = _mel_to_linear(_db_to_amp(D + hparams.ref_level_db), hparams)  # Convert back to linear
  File "D:\ana\lib\site-packages\aukit\audio_griffinlim.py", line 353, in _mel_to_linear
    _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
  File "<__array_function__ internals>", line 6, in pinv
  File "D:\ana\lib\site-packages\numpy\linalg\linalg.py", line 2003, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
  File "<__array_function__ internals>", line 6, in svd
  File "D:\ana\lib\site-packages\numpy\linalg\linalg.py", line 1661, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "D:\ana\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
INFO:tensorflow:Error reported to Coordinator: <class 'numpy.linalg.LinAlgError'>, SVD did not converge
INFO:tensorflow:Error reported to Coordinator: <class 'numpy.linalg.LinAlgError'>, SVD did not converge
2020-08-06 14:00:51.548863: W tensorflow/core/kernels/queue_base.cc:277] _1_datafeeder/eval_queue: Skipping cancelled enqueue attempt with queue not closed
2020-08-06 14:00:51.549330: W tensorflow/core/kernels/queue_base.cc:277] _0_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed

**Comment by wenshitao** [comment]
环境重新安装多次依旧显示这个错误 系统win10 python 3.7 麻烦看一下谢谢

**Comment by KuangDD** [comment]
numpy的版本试一试1.16.4

**Comment by wenshitao** [comment]
感谢您的回复已经测试还是不行呢

**Comment by KuangDD** [comment]
报错的是wav = audio.inv_mel_spectrogram(mel_prediction.T, hparams)，检查一下mel_prediction是怎样的数据，可以可视化看下。

主要看下是否是空值，或者是特殊情况。

上述代码只是保存一下中间结果，不是训练的必要步骤，可以用try忽略掉，或者直接注释掉，把模型跑通。
