### ISSUE TITLE
run synthesizer_preprocess_audio.py error

### ISSUE THREAD

**Issue by Kyantei** [KuangDD/zhrtvc#34]
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 40, in <module>
    args.hparams = hparams.parse(args.hparams)
TypeError: 'NoneType' object is not callable

**Comment by lloves** [comment]
同样遇到这个问题

**Comment by lloves** [comment]
args.hparams = hparams

**Comment by JinghaoZ** [comment]
@lloves 
谢谢，想请教一下如何修改synthesizer_train.py呢

如果按照这种方式，在运行synthesizer_train.py时出现了
Traceback (most recent call last):
  File "synthesizer_train.py", line 59, in <module>
    tacotron_train(args, log_dir, hparams)
  File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 410, in tacotron_train
    return train(log_dir, args, hparams)
  File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 180, in train
    json_dump(obj, path)
  File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 115, in json_dump
    json.dump(obj, open(path, "wt", encoding="utf8"), indent=4, ensure_ascii=False)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type odict_values is not JSON serializable
