### ISSUE TITLE
关于训练synthesizer时的一个断言

### ISSUE THREAD

**Issue by fengfenglov3** [KuangDD/zhrtvc#36]
`!python synthesizer_preprocess_audio.py --datasets_root samples`

Arguments:
datasets_root: samples
datasets: samples
out_dir: samples/SV2TTS/synthesizer
n_processes: 0
skip_existing: True
hparams: 

Using data from:
    samples/samples
_Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 41, in <module>
    preprocess_user(**vars(args))
  File "/content/drive/My Drive/zhrtvc/synthesizer/preprocess.py", line 76, in preprocess_user
    assert all(input_dir.exists() for input_dir in input_dirs)
AssertionError_

**Comment by KuangDD** [comment]
需要先下载资料，放到相应的目录下，具体看readme。

**Comment by fengfenglov3** [comment]
感谢~ 代码已经成功跑起来了，请问训练结束后 是否执行demo文件就可以查看训练效果了
