### ISSUE TITLE
在ubuntu下部署遇到的问题

### ISSUE THREAD

**Issue by JinghaoZ** [KuangDD/zhrtvc#41]
OS: Ubuntu 18.04.3 LTS (GNU/Linux 5.4.0-42-generic x86_64)
Python 3.7.4
执行pip install -r requirements_with_version.txt
数据源：biaobei 按照 #8 里面描述的处理方式

1. python synthesizer_preprocess_audio.py #34 
`Traceback (most recent call last):
File "synthesizer_preprocess_audio.py", line 40, in
args.hparams = hparams.parse(args.hparams)
TypeError: 'NoneType' object is not callable`
**解决方案: args.hparams = hparams.parse(args.hparams)改为 args.hparams = hparams** #34 

2. 运行 synthesizer_train.py 
`Traceback (most recent call last):
File "synthesizer_train.py", line 59, in
tacotron_train(args, log_dir, hparams)
File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 410, in tacotron_train
return train(log_dir, args, hparams)
File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 180, in train
json_dump(obj, path)
File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 115, in json_dump
json.dump(obj, open(path, "wt", encoding="utf8"), indent=4, ensure_ascii=False)
File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/init.py", line 179, in dump
for chunk in iterable:
File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/encoder.py", line 438, in _iterencode
o = _default(o)
File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.class.name} '
TypeError: Object of type odict_values is not JSON serializable`
**解决方案:  修改/zhrtvc/zhrtvc/synthesizer/train.py line 179** 
`obj = list(hparams.values())`

3. 继续运行synthesizer_train.py 
Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [512]
         [[node save/Assign_72 (defined at /home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py:186) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_72:
 Tacotron_model/Tacotron_model/inference/postnet_convolutions/conv_layer_1_postnet_convolutions/batch_normalization/beta/Adam (defined at /home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/models/tacotron.py:495)

Original stack trace for 'save/Assign_72':
  File "synthesizer_train.py", line 59, in <module>
    tacotron_train(args, log_dir, hparams)
  File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 410, in tacotron_train
    return train(log_dir, args, hparams)
  File "/home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py", line 186, in train
    saver = tf.train.Saver(max_to_keep=5)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 350, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 72, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Traceback (most recent call last):
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [512]
         [[{{node save/Assign_72}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/lizhuoxuan/anaconda3/envs/audioenv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [256] rhs shape= [512]
         [[node save/Assign_72 (defined at /home/lizhuoxuan/zhrtvc/zhrtvc/synthesizer/train.py:186) ]]

现在在这里卡住了，希望得到各位的帮助，谢谢

**Comment by KuangDD** [comment]
我的样本数据有没跑通？

**Comment by JinghaoZ** [comment]
> 下载的样本数据有没跑通？

是的，train.txt里面是这样的
../data/samples/biaobei/000001.mp3|mel-biaobei-000001.mp3.npy|embed-biaobei-000001.mp3.npy|35712|142|卡尔普 陪外孙 玩滑梯 。

**Comment by KuangDD** [comment]
这个数据有没跑通呢，把音频数据转为频谱数据，然后训练模型，有没跑通呢？

如果跑通了，那把数据做成样例的形式，看看能否跑通。

**Comment by lawrence124** [comment]
有没有跑通  'python synthesizer_preprocess_embeds.py' ??

**Comment by lawrence124** [comment]
我這一邊，需要按以下順序進行操作:
1) python synthesizer_preprocess_audio.py
2) python synthesizer_preprocess_embeds.py
3) python synthesizer_train.py


**args.hparams = hparams.parse(args.hparams)改为 args.hparams = hparams**  我也有同樣的問題, 我在Windows 10跑的

**Comment by Kyantei** [comment]
> 这个数据有没跑通呢，把音频数据转为频谱数据，然后训练模型，有没跑通呢？
> 
> 如果跑通了，那把数据做成样例的形式，看看能否跑通。

@KuangDD synthesizer_train.py没有跑通
preprocess都跑通了，但是是在将args.hparams = hparams.parse(args.hparams)改为 args.hparams = hparams的情况下跑通的

**Comment by KuangDD** [comment]
谢谢反馈，已经更新修正了这个bug。
