### ISSUE TITLE
用zhvoice重训练synthesizer出现的问题

### ISSUE THREAD

**Issue by fengfenglov3** [KuangDD/zhrtvc#46]
samples: 100% 2400/2400 [00:01<00:00, 1610.78it/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 41, in <module>
    preprocess_user(**vars(args))
  File "/content/drive/My Drive/zhrtvc-master/zhrtvc/synthesizer/preprocess.py", line 96, in preprocess_user
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

在英文版中的issues有找到同样的问题，但是看了作者的回答还是不知道该怎么做。。https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/486

**Comment by KuangDD** [comment]
注意：
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).

原因是没有处理到数据集，或许没有正确传入数据集（数据集路径有误、数据格式不对、不能解析MP3格式）。
请确认数据能够正确处理。

**Comment by fengfenglov3** [comment]
·对于数据集路径，我有使用样例，可以跑通的。之后用的数据集也是按照和样例一样的路径放的（tree也有仔细看过）
·数据格式的话，我是直接用的zhvoice中的一个数据集 （RM中有提到可直接用于这个项目，应该不会是格式的问题吧）
·至于解析MP3格式，很疑惑就是样例也是MP3的格式 能跑，但是所用的数据集MP3和WAV格式我都有试过 都有同样的问题(有安装ffmpeg)
实验环境是 colab python3.6.9

![数据集](https://user-images.githubusercontent.com/61261921/93846944-1beeed00-fcd8-11ea-81ce-9e0dbf68715c.png)
![样例](https://user-images.githubusercontent.com/61261921/93846940-172a3900-fcd8-11ea-832f-6589a5eeb3c8.png)
![tree](https://user-images.githubusercontent.com/61261921/93846938-172a3900-fcd8-11ea-8181-a89a3aad53d2.png)

**Comment by fengfenglov3** [comment]
不过试了在window下能成功处理数据集。
