### ISSUE TITLE
训练单人音色！！

### ISSUE THREAD

**Issue by WIKI2020** [KuangDD/zhrtvc#47]
比日说只模拟某个明星，网上找N段同一明星录音分好大概十来秒一段，按照要求打好标；请问
（1）需要找大概多少小时的录音
（2）这样只训练单人的，最后的效果是不是会很好，基本上能模拟明星本人？

**Comment by WIKI2020** [comment]
另外使用样例模型“models”,代码正常运行输出语音，但下载logs-synx.zip和ge2e_pretrained_iwater.pt替换样例模型的对应路径运行，却存在如下错误：
Traceback (most recent call last):
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64] rhs shape= [128]
	 [[{{node save/Assign_1}}]]

是跟解码器有关吗？

**Comment by WIKI2020** [comment]
INFO:tensorflow:Restoring parameters from ../models/synthesizer/saved_models/logs-syne/checkpoints/model.ckpt-151000
INFO:tensorflow:Restoring parameters from ../models/synthesizer/saved_models/logs-syne/checkpoints/model.ckpt-151000
Traceback (most recent call last):
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64] rhs shape= [128]
	 [[{{node save/Assign_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64] rhs shape= [128]
	 [[node save/Assign_1 (defined at /root/anaconda3/envs/voice/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by KuangDD** [comment]
synx的模型还有hparams.json的文件的，目录结构和syne少许不同，核对一下。

**Comment by WIKI2020** [comment]
看到里面参数不同，都是syne参数*2，应该不用修改吧？

**Comment by WIKI2020** [comment]
训练确可以，推理不行
