### ISSUE TITLE
关于vocoder预处理

### ISSUE THREAD

**Issue by fengfenglov3** [KuangDD/zhrtvc#60]
Arguments:
datasets_root: ../data
model_dir: ../models/synthesizer/saved_models/logs-synz
in_dir: ../data/SV2TTS/synthesizer/.
hparams: 

Traceback (most recent call last):
  File "vocoder_preprocess.py", line 40, in <module>
    run_synthesis(args.in_dir, args.out_dir, args.model_dir, modified_hp)
  File "/content/zhrtvc/zhrtvc/synthesizer/synthesize.py", line 47, in run_synthesis
    checkpoint_fpath = tf.train.get_checkpoint_state(weights_dir).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by xuexidi** [comment]
我强制把checkpoint_fpath写成固定的绝对路径了，注释掉：checkpoint_fpath = tf.train.get_checkpoint_state(weights_dir).model_checkpoint_path这句话

**Comment by fengfenglov3** [comment]
> 我强制把checkpoint_fpath写成固定的绝对路径了，注释掉：checkpoint_fpath = tf.train.get_checkpoint_state(weights_dir).model_checkpoint_path这句话

    
其实我并不是太懂
    model_ckpt="/content/zhrtvc/models/synthesizer/saved_models/logs-synz/checkpoints/checkpoint"
    checkpoint_fpath = os.path.join(model_ckpt)
这个是我在synthesize.py里面修改的代码（注释掉了你提到的那句），还是出现了新的错误，可以分享一下你修改后的代码吗~

另外 我也想用melgan训练的vocoder（有看到你对提问melgan，所以想问问你） 它的train文件--load path是不是指vocoder预训练output的路径，如果是的话。  是不是执行完vocoder_preprocess以后， 再执行 melgan_train就行了
（我看不太明白readme 很难受）

**Comment by fengfenglov3** [comment]
> 我强制把checkpoint_fpath写成固定的绝对路径了，注释掉：checkpoint_fpath = tf.train.get_checkpoint_state(weights_dir).model_checkpoint_path这句话

另外很感谢你回复我的问题，然后我可以加一下你的QQ或者微信吗？
复现过程中，我总是有些很基础的问题 不太会，又迫切想做出来。
更提不出什么有深度和技术性的问题，所以每次在平台上提问都感觉尬尬的T_T
如果你愿意的话 可以私发一下我的邮箱541567232@qq.com 谢谢您~
