### ISSUE TITLE
关于Melletron训练过程中突然梯度爆炸的疑问

### ISSUE THREAD

**Issue by xuexidi** [KuangDD/zhrtvc#79]
**作者您好，非常感谢那你的开源！**
我对您开源的sv2tts部分探索得差不多了，上周五开始着手训练您提供的Mellotron，但是今天来看训练的时候**发现训练到10万步左右的时候突然梯度爆炸了**，程序也自动终止了，**日志信息如下**：

Epoch-66:  34%|████████████████▊                                 | 666/1974 [17:02<33:25,  1.53s/it]WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
Train loss 130950 nan Grad Norm nan 2.11s/it
Validation loss 130950:       nan

Traceback (most recent call last):
  File "mellotron_train.py", line 80, in <module>
    train(hparams=hparams, **args.__dict__)
  File "/home/pxdevice/xue/Mellotron/zhrtvc/mellotron/train.py", line 363, in train
    hparams.distributed_run, rank, outdir=Path(output_directory), hparams=hparams)
  File "/home/pxdevice/xue/Mellotron/zhrtvc/mellotron/train.py", line 207, in validate
    logger.log_validation(val_loss, model, y, y_pred, iteration, x)
  File "/home/pxdevice/xue/Mellotron/zhrtvc/mellotron/logger.py", line 34, in log_validation
    self.add_histogram(tag, value.data.cpu().numpy(), iteration)
  File "/home/pxdevice/anaconda3/envs/ptf/lib/python3.6/site-packages/tensorboardX/writer.py", line 503, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime)
  File "/home/pxdevice/anaconda3/envs/ptf/lib/python3.6/site-packages/tensorboardX/summary.py", line 210, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/home/pxdevice/anaconda3/envs/ptf/lib/python3.6/site-packages/tensorboardX/summary.py", line 248, in make_histogram
    raise ValueError('The histogram is empty, please file a bug report.')
ValueError: The histogram is empty, please file a bug report.

**训练时的配置：**
数据集：AISHELL3，未进行其他预处理(未进行音量归一化+aukit降噪，只是简单切除静音了)，直接用的mellotron的preprocess.py预处理数据
模式：mspk(后续会再尝试rtvc模式)
batchsize：32
其他诸如学习率等参数配置保持跟您提供的代码一致

**其他信息：我查看了一下**
1、训练到大约130950 的时候突然：Train loss 130950 nan Grad Norm nan 2.11s/it
2、观察tensorboard里记录的信息，在130950 step之前大体都挺正常的，就是在87k step的时候的Grad Norm有一个3e+3左右尖峰，但随后又回复正常了。

**【疑问】**
所以这边向请教您一下，您在训练Mellotron的时候碰到过这个问题吗？我不确定是数据预处理的哪里细节出问题了(预处理安利来说应该没问题，直接用的是你提供的preprocess.py)，还是数据集本身的问题，所以想请教您一下，非常感谢！~

**Comment by blackeyecircles** [comment]
请问这个问题后续情况如何，rtvc模式尝试情况如何？

**Comment by blackeyecircles** [comment]
请问这个问题后续情况如何，rtvc模式尝试情况如何？

**Comment by blackeyecircles** [comment]
另外看到您修改了默认的batch 从4到32，我这边在1080ti上训练AISHELL3完整数据，batch为4的情况训练速度为 2sec/item, 调整为32后速度降到大概18sec/item, 训练一个完整的epoch需要24h，比您的1.5sec/item 差了很多倍，请问您的显卡是什么类型，是否调整过什么默认的参数，谢谢！

**Comment by xuexidi** [comment]
> 另外看到您修改了默认的batch 从4到32，我这边在1080ti上训练AISHELL3完整数据，batch为4的情况训练速度为 2sec/item, 调整为32后速度降到大概18sec/item, 训练一个完整的epoch需要24h，比您的1.5sec/item 差了很多倍，请问您的显卡是什么类型，是否调整过什么默认的参数，谢谢！

@blackeyecircles 
您好，总体来说，我自己用AISHELL3数据集训练Mellotron能收敛，但是不考虑克隆，只考虑multispeaker性能的话，感觉效果没有sv2tts好。我还没有自己去训练与之适配的waveglow哈。
显卡是V100 32G显存的显卡。Melltron训练确实会比较慢~

**Comment by blackeyecircles** [comment]
谢谢您的回复，我猜测训练速度慢也可能和数据集某些音频的长度有关，请问您使用的是mspk模式能收敛吗？对每个说话人只有300～500句能直接训练收敛而不需要finetune，这确实很好了
