### ISSUE TITLE
TypeError: 'Tacotron2' object is not subscriptable

### ISSUE THREAD

**Issue by c1a1o1** [KuangDD/zhrtvc#82]
F:\ProgramData\Anaconda3\python.exe F:/work/zhrtvc-master/zhrtvc/mellotron_inference.py
Running a test of your configuration...

Traceback (most recent call last):
  File "F:/work/zhrtvc-master/zhrtvc/mellotron_inference.py", line 152, in <module>
    texts_path=texts_path)
  File "F:\work\zhrtvc-master\zhrtvc\mellotron\inference.py", line 139, in __init__
    self.model.load_state_dict(torch.load(model_path, map_location=self.device)['state_dict'])
TypeError: 'Tacotron2' object is not subscriptable

Process finished with exit code 1

**Comment by givemeareasonLi** [comment]
have the same problem
遇到同样的问题

**Comment by X-CCS** [comment]
@c1a1o1 @givemeareasonLi 请问该问题有解决吗？应该是模型结构不一样的问题

**Comment by givemeareasonLi** [comment]
@c1a1o1 @X-CCS  我试了下，把mellotron_inference.py中['state_dict'] 改为state_dict()，把waveglow_inference.py中['model']和下面的一行代码删除
change the ['state_dict'] in mellotron_inference.py to state_dict()
delete ['model'] and the next line in waveglow_inference.py

**Comment by lihua8848** [comment]
请问
导入作者给的mellotron.kuangdd-rtvc.pt
在进行mellotron_train.py训练时，出现'Tacotron2' object is not subscriptable
@givemeareasonLi 在进行您建议的操作后出现错误，如下

Error(s) in loading state_dict for Tacotron2:
	size mismatch for embedding.weight: copying a param with shape torch.Size([145, 512]) from checkpoint, the shape in current model is torch.Size([145, 256]).
	size mismatch for encoder.convolutions.0.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for encoder.convolutions.0.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.0.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.0.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.0.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.0.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.1.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for encoder.convolutions.1.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.1.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.1.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.1.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.1.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.2.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for encoder.convolutions.2.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.2.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.2.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.2.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.convolutions.2.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encoder.lstm.weight_ih_l0: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([512, 256]).
	size mismatch for encoder.lstm.weight_hh_l0: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([512, 128]).
	size mismatch for encoder.lstm.bias_ih_l0: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.lstm.bias_hh_l0: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.lstm.weight_ih_l0_reverse: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([512, 256]).
	size mismatch for encoder.lstm.weight_hh_l0_reverse: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([512, 128]).
	size mismatch for encoder.lstm.bias_ih_l0_reverse: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encoder.lstm.bias_hh_l0_reverse: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for decoder.prenet.layers.0.linear_layer.weight: copying a param with shape torch.Size([256, 80]) from checkpoint, the shape in current model is torch.Size([128, 80]).
	size mismatch for decoder.prenet.layers.1.linear_layer.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([128, 128]).
	size mismatch for decoder.attention_rnn.weight_ih: copying a param with shape torch.Size([4096, 832]) from checkpoint, the shape in current model is torch.Size([2048, 416]).
	size mismatch for decoder.attention_rnn.weight_hh: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for decoder.attention_rnn.bias_ih: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for decoder.attention_rnn.bias_hh: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for decoder.attention_layer.query_layer.linear_layer.weight: copying a param with shape torch.Size([128, 1024]) from checkpoint, the shape in current model is torch.Size([64, 512]).
	size mismatch for decoder.attention_layer.memory_layer.linear_layer.weight: copying a param with shape torch.Size([128, 576]) from checkpoint, the shape in current model is torch.Size([64, 288]).
	size mismatch for decoder.attention_layer.v.linear_layer.weight: copying a param with shape torch.Size([1, 128]) from checkpoint, the shape in current model is torch.Size([1, 64]).
	size mismatch for decoder.attention_layer.location_layer.location_conv.conv.weight: copying a param with shape torch.Size([32, 2, 31]) from checkpoint, the shape in current model is torch.Size([16, 2, 31]).
	size mismatch for decoder.attention_layer.location_layer.location_dense.linear_layer.weight: copying a param with shape torch.Size([128, 32]) from checkpoint, the shape in current model is torch.Size([64, 16]).
	size mismatch for decoder.decoder_rnn.weight_ih: copying a param with shape torch.Size([4096, 1600]) from checkpoint, the shape in current model is torch.Size([2048, 800]).
	size mismatch for decoder.decoder_rnn.weight_hh: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
	size mismatch for decoder.decoder_rnn.bias_ih: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for decoder.decoder_rnn.bias_hh: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
	size mismatch for decoder.linear_projection.linear_layer.weight: copying a param with shape torch.Size([80, 1600]) from checkpoint, the shape in current model is torch.Size([80, 800]).
	size mismatch for decoder.gate_layer.linear_layer.weight: copying a param with shape torch.Size([1, 1600]) from checkpoint, the shape in current model is torch.Size([1, 800]).
	size mismatch for postnet.convolutions.0.0.conv.weight: copying a param with shape torch.Size([512, 80, 5]) from checkpoint, the shape in current model is torch.Size([256, 80, 5]).
	size mismatch for postnet.convolutions.0.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.0.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.0.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.0.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.0.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.1.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for postnet.convolutions.1.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.1.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.1.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.1.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.1.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.2.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for postnet.convolutions.2.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.2.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.2.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.2.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.2.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.3.0.conv.weight: copying a param with shape torch.Size([512, 512, 5]) from checkpoint, the shape in current model is torch.Size([256, 256, 5]).
	size mismatch for postnet.convolutions.3.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.3.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.3.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.3.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.3.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for postnet.convolutions.4.0.conv.weight: copying a param with shape torch.Size([80, 512, 5]) from checkpoint, the shape in current model is torch.Size([80, 256, 5]).
	size mismatch for speaker_embedding.weight: copying a param with shape torch.Size([64, 256]) from checkpoint, the shape in current model is torch.Size([32, 32]).
	size mismatch for speaker_embedding.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
