### ISSUE TITLE
AttributeError: Can't pickle local object 'TacotronSTFT.griffin_lim.<locals>.<lambda>'

### ISSUE THREAD

**Issue by Jungle-liu** [KuangDD/zhrtvc#84]
epoch走到第十个epoch时突然报错。
Traceback (most recent call last):
  File "D:/xm/语音项目/zhrtvc-master/zhrtvc/mellotron_train.py", line 80, in <module>
    train(hparams=hparams, **args.__dict__)
  File "D:\xm\语音项目\zhrtvc-master\zhrtvc\mellotron\train.py", line 373, in train
    hparams.distributed_run, rank, outdir=Path(output_directory), hparams=hparams)
  File "D:\xm\语音项目\zhrtvc-master\zhrtvc\mellotron\train.py", line 154, in validate
    for i, batch in enumerate(val_loader):
  File "D:\Anaconda3\envs\tf\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\envs\tf\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\tf\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\tf\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\tf\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\tf\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\tf\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TacotronSTFT.griffin_lim.<locals>.<lambda>'

进程已结束，退出代码 1

**Comment by KuangDD** [comment]
最新版本v1.3.16已修复这个bug，请更新代码。
